name: CI-Send

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: CI-Send
        uses: wadeww/send-email-action@master
        with:
         server_address: smtp.gmail.com
         port: 465
         username: ${{secrets.MAIL_USERNAME}}
         password: ${{secrets.MAIL_PASSWORD}}
         subject: BD Callejeros - Tarea en proceso
         body: Hola, soy Jackson, el gato robot, se están modificando los datos de la base de datos. Se te notificará en cuanto se termine. Miau.
         to: soniaperezsanchez44@gmail.com, pasaje_matalascanas@hotmail.com, suareztocino.00@icloud.com
         from: noreply@callejerosdelepe.org
